DROP INDEX APIKEY_UNIQUE;
ALTER TABLE USER_ DROP COLUMN IF EXISTS APIKEY;
ALTER TABLE USER_ ADD COLUMN IF NOT EXISTS TOTP CHAR(16) NULL DEFAULT NULL;
ALTER TABLE USER_ ADD ALLOW_EXTERNAL CHAR(1) NOT NULL DEFAULT '0';

INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('esadmin', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('fhir', '1');